### ISSUE TITLE
Notifications with wrong content and in wrong language

### ISSUE THREAD

**Issue by cdipe** [academic-moodle-cooperation/moodle-mod_publication#50]
Using Moodle 3.9.7 and Student Folder 3.9.0

- Notifications to students about approved / not approved document are mixed up
- Language in Teacher and Student notifications are wrong

Attached is a PDF with more details and screen shots.

[Student Folder notifications problem report.pdf](https://github.com/academic-moodle-cooperation/moodle-mod_publication/files/6763947/Student.Folder.notifications.problem.report.pdf)

**Comment by tjettmers** [comment]
@cdipe maybe identical with https://github.com/academic-moodle-cooperation/moodle-mod_publication/issues/41 ? should has been fixed with student folder 3.10

**Comment by cdipe** [comment]
@tjettmers it looks like it could be part of the problem.
But there is also the mystery of the extra word in the text string (approved" that is hard coded, but still don't show in the mail.
And, the user's language preferences being ignored.
This is a great plugin, the functionality has been long asked for by our teachers! I'm glad to hear there's a new version coming up, will it work with the 3.9 versions of Moodle?

**Comment by goggo24** [comment]
I'm not sure if the language of the notification isn't trigged by the course language and not by the user's language preference - i will ask and come back to you.

As already mentioned above some of the errors have been already fixed with v.3.10.0 of the plugin - see https://github.com/academic-moodle-cooperation/moodle-mod_publication/issues/41. E.g. the hardcoded word - approved was not duplicated because the placeholder contained only the word not. Can you try it with a newer version? 

Note: our Plugins only work with the corresponding Moodle Core Version. So v3.10 of publication under Moodle core 3.10 - if you want to use it, you have to change the required version in the version.php - however, we do not assume any guarantee, that it works under a minor versions, because we haven't tested it.

**Comment by cdipe** [comment]
@goggo24 ok thank you! (It would be great to have "back ported" to Moodle 3.9, since that is a LTS version that we and a lot of other users will have for a while.)

**Comment by goggo24** [comment]
As 3.9 of Moodle Core is no longer supported for general bug fixes, we won't fix this bug. Please upgrade to a higher version - thanks.

**Comment by cdipe** [comment]
@goggo24 done, that was a while ago ;)
